# DataFrames

Throughout the course, most of our data exploration will be done with DataFrames. DataFrames are an extremely powerful tool and a natural extension of the Pandas Series. By definition all a DataFrame is:

**A Pandas DataFrame consists of multiple Pandas Series that share index values.**

In [1]:
import numpy as np
import pandas as pd
np.random.seed(101)
data = np.random.randint(0,50,(5,4))

In [2]:
data

array([[31, 11, 17,  6],
       [23, 11, 47,  9],
       [13, 40,  4, 40],
       [28,  0, 46,  5],
       [12, 29, 40, 49]])

In [3]:
rows = ['SYD', 'MEL', 'CAN', 'BRI', 'PER']

In [4]:
columns = ['JAN', 'FEB', 'MAR', 'APR']

In [5]:
df = pd.DataFrame(data=data)
df

    0   1   2   3
0  31  11  17   6
1  23  11  47   9
2  13  40   4  40
3  28   0  46   5
4  12  29  40  49

In [6]:
df = pd.DataFrame(data=data,index=rows)
df

      0   1   2   3
SYD  31  11  17   6
MEL  23  11  47   9
CAN  13  40   4  40
BRI  28   0  46   5
PER  12  29  40  49

In [7]:
df = pd.DataFrame(data=data,columns=columns)
df

   JAN  FEB  MAR  APR
0   31   11   17    6
1   23   11   47    9
2   13   40    4   40
3   28    0   46    5
4   12   29   40   49

In [8]:
df = pd.DataFrame(data=data,index=rows,columns=columns)
df

     JAN  FEB  MAR  APR
SYD   31   11   17    6
MEL   23   11   47    9
CAN   13   40    4   40
BRI   28    0   46    5
PER   12   29   40   49

You have two options when reading a file with pandas:

1. The code may look like this :   df = pd.read_csv('datafile.csv') - this is when your csv file you want to import is in the same folder loation of your notebook.
        
2. The code may look like this :  df = pd.read_csv("C:\\Projects\\ML\\files\\datafile.csv")v- this is to pass the whole file path if the file is in a different directory

<h1>Context</h1>
The Matildas - the Australian women's national football team - have played 161 full internationals since the start of 2015. Each row of this dataset is one match: who we played, the year, goals scored and conceded, the crowd, whether it was played in Australia, friendly or tournament, and the result.

<h2>Acknowledgements</h2>
Match results compiled from the Wikipedia match record, cross-checked against the open women's international results dataset by Mart Jürisoo. Attendance is missing for some older away matches - it was never recorded. Compiled August 2026.

In [9]:
df = pd.read_csv('data/matildas.csv')

In [10]:
df

,opponent,year,goals_scored,goals_conceded,attendance,in_australia,match_type,result
0,North Korea,2015,2,1,NaN,No,Friendly,W
1,New Zealand,2015,3,2,NaN,No,Friendly,W
2,Netherlands,2015,1,0,NaN,No,Tournament,W
3,England,2015,0,3,NaN,No,Tournament,L
4,Finland,2015,3,0,NaN,No,Tournament,W
...,...,...,...,...,...,...,...,...
156,Japan,2026,0,1,74397.0,Yes,Tournament,L
157,Malawi,2026,5,0,NaN,No,Tournament,W
158,Kenya,2026,2,0,NaN,No,Tournament,W
159,Mexico,2026,0,1,23167.0,Yes,Friendly,L
160,Mexico,2026,3,1,18441.0,Yes,Friendly,W

In [11]:
df.columns

Index(['opponent', 'year', 'goals_scored', 'goals_conceded', 'attendance',
       'in_australia', 'match_type', 'result'],
      dtype='object')

In [12]:
df.index

RangeIndex(start=0, stop=161, step=1)

In [13]:
df.head(5) #Read the first 5 records

,opponent,year,goals_scored,goals_conceded,attendance,in_australia,match_type,result
0,North Korea,2015,2,1,NaN,No,Friendly,W
1,New Zealand,2015,3,2,NaN,No,Friendly,W
2,Netherlands,2015,1,0,NaN,No,Tournament,W
3,England,2015,0,3,NaN,No,Tournament,L
4,Finland,2015,3,0,NaN,No,Tournament,W

In [14]:
df.tail(5) #Read the last five records

,opponent,year,goals_scored,goals_conceded,attendance,in_australia,match_type,result
156,Japan,2026,0,1,74397.0,Yes,Tournament,L
157,Malawi,2026,5,0,NaN,No,Tournament,W
158,Kenya,2026,2,0,NaN,No,Tournament,W
159,Mexico,2026,0,1,23167.0,Yes,Friendly,L
160,Mexico,2026,3,1,18441.0,Yes,Friendly,W

In [15]:
df.info() #Information on the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opponent        161 non-null    object
 1   year            161 non-null    int64
 2   goals_scored    161 non-null    int64
 3   goals_conceded  161 non-null    int64
 4   attendance      101 non-null    float64
 5   in_australia    161 non-null    object
 6   match_type      161 non-null    object
 7   result          161 non-null    object
dtypes: float64(1), int64(3), object(4)
memory usage: 10.2+ KB

In [16]:
len(df) #length or number of records in the data frame

161

In [17]:
df.describe() #describe the dataframe on some commonly used statistical parameters

              year  goals_scored  goals_conceded    attendance
count   161.000000    161.000000      161.000000    101.000000
mean   2020.453416      2.273292        1.192547  21919.128713
std       3.517724      2.392665        1.325309  19822.160297
min    2015.000000      0.000000        0.000000      0.000000
25%    2017.000000      1.000000        0.000000   8678.000000
50%    2021.000000      2.000000        1.000000  15748.000000
75%    2023.000000      3.000000        2.000000  28019.000000
max    2026.000000     18.000000        7.000000  76798.000000

In [18]:
df.describe().transpose() #Tranpose the description of the dataframe - row become columns
#columns become rows

,count,mean,std,min,25%,50%,75%,max
year,161.0,2020.453416,3.517724,2015.0,2017.0,2021.0,2023.0,2026.0
goals_scored,161.0,2.273292,2.392665,0.0,1.0,2.0,3.0,18.0
goals_conceded,161.0,1.192547,1.325309,0.0,0.0,1.0,2.0,7.0
attendance,101.0,21919.128713,19822.160297,0.0,8678.0,15748.0,28019.0,76798.0

<h1> Some common selection and Indexing functions with Data frame </h1>
<h4> Read the data from a single column </h4>

In [19]:
df['attendance']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
        ...
156    74397.0
157        NaN
158        NaN
159    23167.0
160    18441.0
Name: attendance, Length: 161, dtype: float64

In [20]:
type(df['attendance'])

pandas.core.series.Series

In [21]:
# Its a python list of column names, that's why needs double brackets.
df[['attendance','goals_scored']]

     attendance  goals_scored
0           NaN             2
1           NaN             3
2           NaN             1
3           NaN             0
4           NaN             3
..          ...           ...
156     74397.0             0
157         NaN             5
158         NaN             2
159     23167.0             0
160     18441.0             3

[161 rows x 2 columns]

<h4> Creating a new column for the Dataframe </h4>

In [22]:
df['goal_difference'] = df['goals_scored'] - df['goals_conceded']

In [23]:
df.head()

,opponent,year,goals_scored,goals_conceded,attendance,in_australia,match_type,result,goal_difference
0,North Korea,2015,2,1,NaN,No,Friendly,W,1
1,New Zealand,2015,3,2,NaN,No,Friendly,W,1
2,Netherlands,2015,1,0,NaN,No,Tournament,W,1
3,England,2015,0,3,NaN,No,Tournament,L,-3
4,Finland,2015,3,0,NaN,No,Tournament,W,3

In [24]:
df['total_goals'] = df['goals_scored'] + df['goals_conceded']

In [25]:
df.head()

,opponent,year,goals_scored,goals_conceded,attendance,in_australia,match_type,result,goal_difference,total_goals
0,North Korea,2015,2,1,NaN,No,Friendly,W,1,3
1,New Zealand,2015,3,2,NaN,No,Friendly,W,1,5
2,Netherlands,2015,1,0,NaN,No,Tournament,W,1,1
3,England,2015,0,3,NaN,No,Tournament,L,-3,3
4,Finland,2015,3,0,NaN,No,Tournament,W,3,3

<h4> Manipulating columns using Numpy </h4>

In [26]:
# Because pandas is based on numpy, we get awesome capabilities with numpy's universal functions!
df['attendance_thousands'] = np.round(df['attendance'] / 1000, 2)

<h4>Removing columns from the data frame </h4>

In [27]:
df = df.drop("goal_difference",axis=1)

In [28]:
df.head()

,opponent,year,goals_scored,goals_conceded,attendance,in_australia,match_type,result,total_goals,attendance_thousands
0,North Korea,2015,2,1,NaN,No,Friendly,W,3,NaN
1,New Zealand,2015,3,2,NaN,No,Friendly,W,5,NaN
2,Netherlands,2015,1,0,NaN,No,Tournament,W,1,NaN
3,England,2015,0,3,NaN,No,Tournament,L,3,NaN
4,Finland,2015,3,0,NaN,No,Tournament,W,3,NaN

In [29]:
df.index

RangeIndex(start=0, stop=161, step=1)

In [30]:
df.set_index('opponent')

,year,goals_scored,goals_conceded,attendance,in_australia,match_type,result,total_goals,attendance_thousands
opponent,,,,,,,,,
North Korea,2015,2,1,NaN,No,Friendly,W,3,NaN
New Zealand,2015,3,2,NaN,No,Friendly,W,5,NaN
Netherlands,2015,1,0,NaN,No,Tournament,W,1,NaN
England,2015,0,3,NaN,No,Tournament,L,3,NaN
Finland,2015,3,0,NaN,No,Tournament,W,3,NaN
...,...,...,...,...,...,...,...,...,...
Japan,2026,0,1,74397.0,Yes,Tournament,L,1,74.40
Malawi,2026,5,0,NaN,No,Tournament,W,5,NaN
Kenya,2026,2,0,NaN,No,Tournament,W,2,NaN
Mexico,2026,0,1,23167.0,Yes,Friendly,L,1,23.17
Mexico,2026,3,1,18441.0,Yes,Friendly,W,4,18.44

In [31]:
df = df.reset_index()

In [32]:
df.head()

,index,opponent,year,goals_scored,goals_conceded,attendance,in_australia,match_type,result,total_goals,attendance_thousands
0,0,North Korea,2015,2,1,NaN,No,Friendly,W,3,NaN
1,1,New Zealand,2015,3,2,NaN,No,Friendly,W,5,NaN
2,2,Netherlands,2015,1,0,NaN,No,Tournament,W,1,NaN
3,3,England,2015,0,3,NaN,No,Tournament,L,3,NaN
4,4,Finland,2015,3,0,NaN,No,Tournament,W,3,NaN

<h1> Work with Rows </h1>

In [33]:
df.iloc[0]

index                             0
opponent                North Korea
year                           2015
goals_scored                      2
goals_conceded                    1
attendance                      NaN
in_australia                     No
match_type                 Friendly
result                            W
total_goals                       3
attendance_thousands            NaN
Name: 0, dtype: object

In [34]:

df.loc[2]

index                             2
opponent                Netherlands
year                           2015
goals_scored                      1
goals_conceded                    0
attendance                      NaN
in_australia                     No
match_type               Tournament
result                            W
total_goals                       1
attendance_thousands            NaN
Name: 2, dtype: object

In [35]:
df.iloc[0:4]

,index,opponent,year,goals_scored,goals_conceded,attendance,in_australia,match_type,result,total_goals,attendance_thousands
0,0,North Korea,2015,2,1,NaN,No,Friendly,W,3,NaN
1,1,New Zealand,2015,3,2,NaN,No,Friendly,W,5,NaN
2,2,Netherlands,2015,1,0,NaN,No,Tournament,W,1,NaN
3,3,England,2015,0,3,NaN,No,Tournament,L,3,NaN